# 特征词转化为 One-hot 矩阵

In [43]:
import torch
import numpy as np
import torch.nn as nn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 分割句子到单一的汉字
def n_gram(target, n):
  # 提取n个字，同时通过＃1开始的字移动
  return [ target[idx:idx + n] for idx in range(len(target) - n + 1)]

# 语料库
corpus=[n_gram('我爱中国', 1),n_gram('我爱北京天安门', 1)]

# 合并语料库
words = sorted(set(np.concatenate(corpus)))
print(words)

# 为每个汉字进行整型编码
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(words)
print(integer_encoded)

# one-hot 编码器
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)


['中', '京', '北', '国', '天', '安', '我', '爱', '门']
[0 1 2 3 4 5 6 7 8]
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


# 特征词转化为 tf-idf 矩阵

# 利用 word2vec 进行 词向量训练

# word2vec 简单应用

# 利用 one-hot 、TF-idf、word2vec 构建句向量，然后 采用 朴素贝叶斯、条件随机场做分类